/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AprendaRouteImport } from './routes/aprenda'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CriadoresRouteImport } from './routes/criadores'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthedCheckoutRouteImport } from './routes/_authed.checkout'
import { Route as AuthedProfileRouteImport } from './routes/_authed.profile'
import { Route as AuthedWalletsRouteImport } from './routes/_authed.wallets'
import { Route as NftNftIdRouteImport } from './routes/nft.$nftId'
import { Route as AuthedOrdersOrderIdRouteImport } from './routes/_authed.orders.$orderId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AprendaRoute = AprendaRouteImport.update({
  id: '/aprenda',
  path: '/aprenda',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CriadoresRoute = CriadoresRouteImport.update({
  id: '/criadores',
  path: '/criadores',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedCheckoutRoute = AuthedCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProfileRoute = AuthedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedWalletsRoute = AuthedWalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => AuthedRoute,
} as any)
const NftNftIdRoute = NftNftIdRouteImport.update({
  id: '/nft/$nftId',
  path: '/nft/$nftId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedOrdersOrderIdRoute = AuthedOrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aprenda': typeof AprendaRoute
  '/cart': typeof CartRoute
  '/criadores': typeof CriadoresRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/checkout': typeof AuthedCheckoutRoute
  '/profile': typeof AuthedProfileRoute
  '/wallets': typeof AuthedWalletsRoute
  '/nft/$nftId': typeof NftNftIdRoute
  '/orders/$orderId': typeof AuthedOrdersOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aprenda': typeof AprendaRoute
  '/cart': typeof CartRoute
  '/criadores': typeof CriadoresRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/checkout': typeof AuthedCheckoutRoute
  '/profile': typeof AuthedProfileRoute
  '/wallets': typeof AuthedWalletsRoute
  '/nft/$nftId': typeof NftNftIdRoute
  '/orders/$orderId': typeof AuthedOrdersOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/aprenda': typeof AprendaRoute
  '/cart': typeof CartRoute
  '/criadores': typeof CriadoresRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authed/checkout': typeof AuthedCheckoutRoute
  '/_authed/profile': typeof AuthedProfileRoute
  '/_authed/wallets': typeof AuthedWalletsRoute
  '/nft/$nftId': typeof NftNftIdRoute
  '/_authed/orders/$orderId': typeof AuthedOrdersOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aprenda'
    | '/cart'
    | '/criadores'
    | '/login'
    | '/signup'
    | '/checkout'
    | '/profile'
    | '/wallets'
    | '/nft/$nftId'
    | '/orders/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aprenda'
    | '/cart'
    | '/criadores'
    | '/login'
    | '/signup'
    | '/checkout'
    | '/profile'
    | '/wallets'
    | '/nft/$nftId'
    | '/orders/$orderId'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/aprenda'
    | '/cart'
    | '/criadores'
    | '/login'
    | '/signup'
    | '/_authed/checkout'
    | '/_authed/profile'
    | '/_authed/wallets'
    | '/nft/$nftId'
    | '/_authed/orders/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  AprendaRoute: typeof AprendaRoute
  CartRoute: typeof CartRoute
  CriadoresRoute: typeof CriadoresRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  NftNftIdRoute: typeof NftNftIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aprenda': {
      id: '/aprenda'
      path: '/aprenda'
      fullPath: '/aprenda'
      preLoaderRoute: typeof AprendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criadores': {
      id: '/criadores'
      path: '/criadores'
      fullPath: '/criadores'
      preLoaderRoute: typeof CriadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/checkout': {
      id: '/_authed/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof AuthedCheckoutRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/profile': {
      id: '/_authed/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthedProfileRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/wallets': {
      id: '/_authed/wallets'
      path: '/wallets'
      fullPath: '/wallets'
      preLoaderRoute: typeof AuthedWalletsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/nft/$nftId': {
      id: '/nft/$nftId'
      path: '/nft/$nftId'
      fullPath: '/nft/$nftId'
      preLoaderRoute: typeof NftNftIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/orders/$orderId': {
      id: '/_authed/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof AuthedOrdersOrderIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedCheckoutRoute: typeof AuthedCheckoutRoute
  AuthedProfileRoute: typeof AuthedProfileRoute
  AuthedWalletsRoute: typeof AuthedWalletsRoute
  AuthedOrdersOrderIdRoute: typeof AuthedOrdersOrderIdRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedCheckoutRoute: AuthedCheckoutRoute,
  AuthedProfileRoute: AuthedProfileRoute,
  AuthedWalletsRoute: AuthedWalletsRoute,
  AuthedOrdersOrderIdRoute: AuthedOrdersOrderIdRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  AprendaRoute: AprendaRoute,
  CartRoute: CartRoute,
  CriadoresRoute: CriadoresRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  NftNftIdRoute: NftNftIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
